apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magento-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    #nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    #nginx.ingress.kubernetes.io/fastcgi-buffers: "16 16k"
    #nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
spec:
  tls:
    - hosts:
      - {{ .Values.domainMagento }}
      secretName: magento-cert
  rules:
    - host: {{ .Values.domainMagento }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: magento
                port:
                  number: 8080
