apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: magento-cert
spec:
  secretName: magento-cert
  dnsNames:
    - {{ .Values.domainMagento }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
