apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgweb-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domainPgWeb }}
      secretName: pgweb-cert
  rules:
    - host: {{ .Values.domainPgWeb }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nopcommerce-{{ .Values.envAlias }}-pgweb
                port:
                  number: 80
