### Magento ###
magento:
  enabled: true
  nameOverride: magento
  fullnameOverride: magento

  ### To change the configuration, may need to delete PVC for the changes to take effect.
  magentoUseSecureAdmin: true
  magentoUsername: admin
  existingSecret: magento # Must be the same name as $nameOverride
  service:
    type: ClusterIP
    ports:
      http: 80

### Wordpress ###
wordpress:
  enabled: true
  replicaCount: 1
  wordpressScheme: https
  wordpressUsername: admin
  existingSecret: 'wordpress-user-login'

  readinessProbe:
    enabled: false

  ingress:
    enabled: false

  service:
    type: ClusterIP

  mariadb:
    enabled: false

  externalDatabase:
    port: 3306
    database: wordpress
    user: root
    existingSecret: wordpress-db-login

mysql:
  enabled: true
  auth:
    database: wordpress
    existingSecret: wordpress-db-login
