apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: magento
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: magento       # name of the k8s Secret to be created
  data:
  - secretKey: magento-password
    remoteRef:
      key: initial-secret
      property: MAGENTO_PASSWORD
