apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: mariadb-secret       # name of the k8s Secret to be created
  data:
  - secretKey: mariadb-password
    remoteRef:
      key: initial-secret
      property: MARIADB_MAGENTO_PASSWORD
