apiVersion: v2
name: helm-cybertracx
description: A Helm chart for Cybertracx

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql-nopc
    condition: postgresql-nopc.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "12.5.7"

  ### nopCommerce ###
  - name: "generic-app"
    alias: nop-commerce
    condition: nop-commerce.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.17"
