magento:
  enabled: true
  nameOverride: magento
  fullnameOverride: magento
  magentoUseSecureAdmin: true

  service:
    type: ClusterIP
    ports:
      http: 80

  mariadb:
    auth:
      password: xxxxmagentoxxxxx
