### NopCommerce ###
nop-commerce:
  enabled: true
  nameOverride: nopcommerce

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: "nopcommerceteam/nopcommerce"
      tag: "4.60.3"
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
    #volumes:
    #  - name: appsetting
    #    secret:
    #      secretName: carpark-api-appsetting
    #      optional: false
    #volumeMounts:
    #  - name: appsetting
    #    mountPath: /app/appsettings.json
    #    subPath: appsettings.json
  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

  ingress:
    enabled: false

### PostgreSQL ###
postgresql-nopc:
  enabled: true
  fullnameOverride: postgresql-nopc
  auth:
    database: nopcommerce
    existingSecret: nopc-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

### PG Web ###
pgweb:
  enabled: true
  nameOverride: pgweb
  ingress:
    enabled: false
